### ISSUE TITLE
Background image in fullscreen mode shifted

### ISSUE THREAD

**Issue by R0M4N0F5K7** [hteumeuleu/celeste#3]
First of all thank you for that wonderful port.

Sadly and weirdly full screen mode seems broken on my device the background img seems to be shifted to the right bottom corner, the hitboxes still register correct. 
I noticed that if I turn full screen mode off all is fine (just very small obviously), switching it on again shifts the background out of screen again. Reinstall, restarting the device or deleting data didn't change anything. 
I am on the newest OS/SDK version 1.13.0.

https://user-images.githubusercontent.com/15329506/218581281-3933fc9c-6a6f-4743-8376-33a161f06175.mp4

**Comment by hteumeuleu** [comment]
Found it! It was indeed due to 1.13. Sprites are no longer of type `table` but are now `userdata`. I was checking this before moving sprites when changing fullscreen mode. But this wasn't necessary anyway so I simply removed the check. I'll push a beta with this.

**Comment by R0M4N0F5K7** [comment]
@hteumeuleu thanks for the quick fix, do you plan on publishing a new release with this soon? Otherwise I might build it myself, can't wait.

**Comment by hteumeuleu** [comment]
There you go: https://github.com/hteumeuleu/celeste/releases/tag/v1.0.0-beta.2

**Comment by R0M4N0F5K7** [comment]
Downloaded it within the first minute it was available. Great stuff, thank you so much.
And good work!
