### ISSUE TITLE
Marks every future run as "+assist mode" even if it was not used any more...

### ISSUE THREAD

**Issue by R0M4N0F5K7** [hteumeuleu/celeste#4]
Only deleting game data seems to ever remove the "+assist mode" flag if it was ever toggled on, even if it is disabled and the game reset and started without any assistance.
I suppose rechecking if any assist mode flags are set every time a game is started from the start screen would be good.
(Currently it doesn't really matter, but if you ever introduce a high score feature this would be bad).

**Comment by hteumeuleu** [comment]
Thanks, that's definitely not intended. I'll check this out.
